

#################################
# Port Number
#################################
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  banner:
    location: banner/banner.txt

  application:
    name: MultiChat

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    cache: false
    encoding: UTF-8


  #################################
  # SQL Setting
  #################################
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'URL'
    username: 'ID'
    password: 'PW'

  #################################
  # JPA Setting
  #################################

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  #json?? ??
  jackson:
    serialization:
      fail-on-empty-beans: false



###############################
# Log info
###############################
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

###############################
# SEQURITY
###############################
